require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bedragon' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  
  
  target 'bedragonTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.3.0'})
  post_install do |installer|
    flipper_post_install(installer)
  end


  #use_frameworks!
  #pod 'RNInputMask', path => '../node_modules/react-native-text-input-mask/ios/InputMask'
#pod 'react-native-text-input-mask', path => '../node_modules/react-native-text-input-mask'

end

target 'bedragon-tvOS' do
  # Pods for bedragon-tvOS

  target 'bedragon-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
